### ISSUE TITLE
Type issues and Login method undefined

### ISSUE THREAD

**Issue by RonanKMcGovern** [nasdf/wagmi-magic-connector#1]
I'm using a Vite app with RainbowKit.

Errors:
1. Type issues
```
[{
	"resource": ".../src/config/wagmi.ts",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ id: string; name: string; iconUrl: string; iconBackground: string; createConnector: () => { connector: MagicConnector; }; }' is not assignable to type 'Wallet<Connector<any, any, any>>'.\n  The types of 'createConnector().connector' are incompatible between these types.\n    Type 'MagicConnector' is not assignable to type 'Connector<any, any, any>'.\n      Property 'onAccountsChanged' is protected but type 'MagicConnector' is not a class derived from 'Connector<Provider, Options, Signer>'.",
	"source": "ts",
	"startLineNumber": 115,
	"startColumn": 7,
	"endLineNumber": 115,
	"endColumn": 40
}]
```

2. Login method undefined after 'npm start' then clicking on the magic button on the RainbowKit modal:

```
act_devtools_backend_compact.js:2367 Error: login method undefined
    at _a.connect (index.ts:49:31)
    at async connect (chunk-VQG3VKOR.js:727:18)
o
```
And my code:

```
import { MagicConnector } from '@nasdf/wagmi-magic-connector'

const apiKey = import.meta.env.VITE_YOUR_MAGIC_CONNECT_API_KEY;

if (!apiKey) {
    throw new Error('API key not found. Please check your environment variables.');
  }

const network = {
  rpcUrl: 'https://poly-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5', // your ethereum, polygon, or optimism mainnet/testnet rpc URL
  chainId: 137,
}

const rainbowMagicConnector = ({ chains }: any) => ({
  id: 'magic',
  name: 'Email',
  iconUrl: 'https://svgshare.com/i/iJK.svg',
  iconBackground: '#fff',
  createConnector: () => {
    const connector = new MagicConnector({
      chains: chains,
      options: {
        apiKey: apiKey as string,
        network: network,
      },
    })
    return {
      connector,
    };
  },
});

export const { chains, provider } = configureChains([polygon], [
  jsonRpcProvider({
    rpc: (chain) => {
      switch (chain.id) {
        case 1:
          return {
            http: "https://eth-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
        case 5:
          return {
            http: "https://eth-goerli.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
        case 137:
          return {
            http: "https://poly-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
        case 43114:
          return {
            http: "https://avax-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
        default:
          return {
            http: "https://eth-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
      }
    },
  }),
]);

export const connectors = connectorsForWallets([
  {
    groupName: "Recommended",
    wallets: [
      coinbaseWallet({ appName: "Trelis Pay", chains }),
      metaMaskWallet({ chains, shimDisconnect: true }),
      walletConnectWallet({ chains }),
      rainbowMagicConnector({ chains }),
    ],
  },...
```

**Comment by nasdf** [comment]
Can you share your `package.json` dependencies?

**Comment by RonanKMcGovern** [comment]
Sure @nasdf :

`{
  "name": "eth-pay",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ajna/pagination": "^1.4.19",
    "@chakra-ui/react": "^2.4.5",
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@hookform/resolvers": "^2.8.10",
    "@nasdf/wagmi-magic-connector": "^0.0.4",
    "@rainbow-me/rainbowkit": "^0.12.3",
    "@tanstack/react-query": "^4.28.0",
    "@xstate/react": "^3.2.1",
    "axios": "^0.27.2",
    "bn.js": "^5.2.1",
    "buffer": "^6.0.3",
    "date-fns": "^2.28.0",
    "ethers": "^5.4.0",
    "framer-motion": "^6.3.5",
    "immer": "^9.0.17",
    "jotai": "^1.7.2",
    "jotai-immer": "^0.1.0",
    "jotai-xstate": "^0.2.0",
    "json-rpc-engine": "^6.1.0",
    "lodash": "^4.17.21",
    "qrcode.react": "^3.0.2",
    "react": "^18.2.0",
    "react-date-range": "^1.4.0",
    "react-dom": "^18.2.0",
    "react-ga": "^3.3.0",
    "react-hook-form": "^7.31.3",
    "react-icons": "^4.4.0",
    "react-intersection-observer": "^9.4.0",
    "react-router-dom": "6",
    "use-debounce": "^8.0.4",
    "wagmi": "^0.12.6",
    "web-vitals": "^2.1.0",
    "web3": "^1.8.0",
    "xstate": "^4.36.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@types/node": "^18.11.18",
    "@types/react": "^18.0.26",
    "@types/react-date-range": "^1.4.3",
    "@types/react-dom": "^18.0.10",
    "@vitejs/plugin-react": "^3.1.0",
    "@vitejs/plugin-react-swc": "^3.2.0",
    "typescript": "^4.9.5",
    "vite": "^4.2.1",
    "vite-plugin-svgr": "^2.4.0",
    "vite-tsconfig-paths": "^4.0.7"
  },
  "scripts": {
    "start": "vite",
    "dev": "vite",
    "build": "tsc && vite build",
    "serve": "vite preview"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by nasdf** [comment]
I think you should be able to safely `// @ts-ignore` the type error.  

The login error can be fixed by calling the following before connecting. 

```javascript
connector.loginWithMagicLink({ email, showUI: true })
```

There's also a more complete example in the readme.

**Comment by RonanKMcGovern** [comment]
Thanks, the issue is that I'm adding this magic connector as a wallet within RainbowKit. Perhaps RainbowKit isn't calling connector.loginWithMagicLink({... and that's the issue. I don't see that issue with https://github.com/Royal-lobster/rainbow-magic-example/issues/1 (a different connector, which gives other issues, but allows login).

```import { connectorsForWallets } from "@rainbow-me/rainbowkit";
import { Chain, configureChains, createClient } from "wagmi";
import { polygon } from "wagmi/chains";
import { jsonRpcProvider } from "wagmi/providers/jsonRpc";
import {
  argentWallet,
  braveWallet,
  coinbaseWallet,
  injectedWallet,
  imTokenWallet,
  metaMaskWallet,
  rainbowWallet,
  walletConnectWallet,
  ledgerWallet,
  trustWallet,
} from '@rainbow-me/rainbowkit/wallets';

import { MagicConnector } from '@nasdf/wagmi-magic-connector'

const apiKey = import.meta.env.VITE_YOUR_MAGIC_CONNECT_API_KEY;

if (!apiKey) {
    throw new Error('API key not found. Please check your environment variables.');
  }

const network = {
  rpcUrl: 'https://poly-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5', // your ethereum, polygon, or optimism mainnet/testnet rpc URL
  chainId: 137,
}

const rainbowMagicConnector = ({ chains }: any) => ({
  id: 'magic',
  name: 'Email',
  iconUrl: 'https://svgshare.com/i/iJK.svg',
  iconBackground: '#fff',
  createConnector: () => {
    const connector = new MagicConnector({
      chains: chains,
      options: {
        apiKey: apiKey as string,
        network: network,
      },
    })
    return {
      connector,
    };
  },
});

const avalanche: Chain = {
  id: 43114,
  name: "Avalanche",
  network: "avalanche",
  nativeCurrency: {
    decimals: 18,
    name: "Avalanche",
    symbol: "AVAX",
  },
  rpcUrls: {
    default: {
      http: ["https://api.avax.network/ext/bc/C/rpc"],
    },
    public: {
      http: ["https://api.avax.network/ext/bc/C/rpc"],
    },
  },
  blockExplorers: {
    etherscan: { name: "SnowTrace", url: "https://snowtrace.io" },
    default: { name: "SnowTrace", url: "https://snowtrace.io" },
  },
  // contracts: {
  //   multicall3: {
  //     address: "0xca11bde05977b3631167028862be2a173976ca11",
  //     blockCreated: 11907934,
  //   },
  // },
};

export const { chains, provider } = configureChains([polygon], [
  jsonRpcProvider({
    rpc: (chain) => {
      switch (chain.id) {
        case 1:
          return {
            http: "https://eth-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
        case 5:
          return {
            http: "https://eth-goerli.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
        case 137:
          return {
            http: "https://poly-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
        case 43114:
          return {
            http: "https://avax-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
        default:
          return {
            http: "https://eth-mainnet.gateway.pokt.network/v1/lb/f3ebd729f40522b268bd0bc5",
          };
      }
    },
  }),
]);

export const connectors = connectorsForWallets([
  {
    groupName: "Recommended",
    wallets: [
      coinbaseWallet({ appName: "Trelis Pay", chains }),
      metaMaskWallet({ chains, shimDisconnect: true }),
      walletConnectWallet({ chains }),
      rainbowMagicConnector({ chains }),
    ],
  },
  {
    groupName: "Others",
    wallets: [
      ledgerWallet({
        chains,
      }),
      rainbowWallet({ chains }),
      braveWallet({
        chains,
        shimDisconnect: true,
      }),
      imTokenWallet({ chains }),
      injectedWallet({
        chains,
        shimDisconnect: true,
      }),
      trustWallet({ chains, shimDisconnect: true }),
    ],
  },
]);

export const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});
```

**Comment by nasdf** [comment]
Yeah that makes sense.  This library was made to be headless so you have to implement the UI yourself. If you want something with a built in UI check out https://github.com/EveripediaNetwork/wagmi-magic-connector

**Comment by RonanKMcGovern** [comment]
Ok, thanks, appreciate the help, and thanks for having built this connector.
